# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Dropbox\Coding\GameSelector\GameSelector.ui'
#
# Created: Fri Oct 25 19:07:42 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameSelector(object):
    def setupUi(self, GameSelector):
        GameSelector.setObjectName(_fromUtf8("GameSelector"))
        GameSelector.setEnabled(True)
        GameSelector.resize(1280, 720)
        self.centralwidget = QtGui.QWidget(GameSelector)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.bgcollectionView = QtGui.QTableWidget(self.centralwidget)
        self.bgcollectionView.setGeometry(QtCore.QRect(270, 0, 1011, 600))
        self.bgcollectionView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.bgcollectionView.setAlternatingRowColors(True)
        self.bgcollectionView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.bgcollectionView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.bgcollectionView.setRowCount(1)
        self.bgcollectionView.setColumnCount(4)
        self.bgcollectionView.setObjectName(_fromUtf8("bgcollectionView"))
        self.bgcollectionView.horizontalHeader().setSortIndicatorShown(False)
        self.bgcollectionView.verticalHeader().setVisible(False)
        self.playtimedial = QtGui.QDial(self.centralwidget)
        self.playtimedial.setGeometry(QtCore.QRect(100, 200, 150, 150))
        self.playtimedial.setMaximum(420)
        self.playtimedial.setSingleStep(10)
        self.playtimedial.setPageStep(20)
        self.playtimedial.setNotchesVisible(True)
        self.playtimedial.setObjectName(_fromUtf8("playtimedial"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 380, 256, 192))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 340, 51, 31))
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.dialmaxlabel = QtGui.QLabel(self.centralwidget)
        self.dialmaxlabel.setGeometry(QtCore.QRect(210, 340, 21, 16))
        self.dialmaxlabel.setObjectName(_fromUtf8("dialmaxlabel"))
        self.dialminlabel = QtGui.QLabel(self.centralwidget)
        self.dialminlabel.setGeometry(QtCore.QRect(120, 340, 21, 16))
        self.dialminlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dialminlabel.setObjectName(_fromUtf8("dialminlabel"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 5, 261, 151))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.bestButton = QtGui.QPushButton(self.frame)
        self.bestButton.setEnabled(False)
        self.bestButton.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.bestButton.setCheckable(True)
        self.bestButton.setObjectName(_fromUtf8("bestButton"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(75, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.recommendedButton = QtGui.QPushButton(self.frame)
        self.recommendedButton.setEnabled(False)
        self.recommendedButton.setGeometry(QtCore.QRect(160, 10, 91, 31))
        self.recommendedButton.setCheckable(True)
        self.recommendedButton.setObjectName(_fromUtf8("recommendedButton"))
        self.Btn1Player = QtGui.QPushButton(self.frame)
        self.Btn1Player.setGeometry(QtCore.QRect(10, 50, 41, 41))
        self.Btn1Player.setCheckable(True)
        self.Btn1Player.setChecked(False)
        self.Btn1Player.setFlat(False)
        self.Btn1Player.setObjectName(_fromUtf8("Btn1Player"))
        self.Btn2Player = QtGui.QPushButton(self.frame)
        self.Btn2Player.setGeometry(QtCore.QRect(60, 50, 41, 41))
        self.Btn2Player.setCheckable(True)
        self.Btn2Player.setObjectName(_fromUtf8("Btn2Player"))
        self.Btn3Player = QtGui.QPushButton(self.frame)
        self.Btn3Player.setGeometry(QtCore.QRect(110, 50, 41, 41))
        self.Btn3Player.setCheckable(True)
        self.Btn3Player.setObjectName(_fromUtf8("Btn3Player"))
        self.Btn4Player = QtGui.QPushButton(self.frame)
        self.Btn4Player.setGeometry(QtCore.QRect(160, 50, 41, 41))
        self.Btn4Player.setCheckable(True)
        self.Btn4Player.setObjectName(_fromUtf8("Btn4Player"))
        self.Btn5Player = QtGui.QPushButton(self.frame)
        self.Btn5Player.setGeometry(QtCore.QRect(210, 50, 41, 41))
        self.Btn5Player.setCheckable(True)
        self.Btn5Player.setObjectName(_fromUtf8("Btn5Player"))
        self.Btn6Player = QtGui.QPushButton(self.frame)
        self.Btn6Player.setGeometry(QtCore.QRect(10, 100, 41, 41))
        self.Btn6Player.setCheckable(True)
        self.Btn6Player.setObjectName(_fromUtf8("Btn6Player"))
        self.Btn7Player = QtGui.QPushButton(self.frame)
        self.Btn7Player.setGeometry(QtCore.QRect(60, 100, 41, 41))
        self.Btn7Player.setCheckable(True)
        self.Btn7Player.setObjectName(_fromUtf8("Btn7Player"))
        self.Btn8Player = QtGui.QPushButton(self.frame)
        self.Btn8Player.setGeometry(QtCore.QRect(110, 100, 41, 41))
        self.Btn8Player.setCheckable(True)
        self.Btn8Player.setObjectName(_fromUtf8("Btn8Player"))
        self.Btn9Player = QtGui.QPushButton(self.frame)
        self.Btn9Player.setGeometry(QtCore.QRect(160, 100, 41, 41))
        self.Btn9Player.setCheckable(True)
        self.Btn9Player.setObjectName(_fromUtf8("Btn9Player"))
        self.Btn10Player = QtGui.QPushButton(self.frame)
        self.Btn10Player.setGeometry(QtCore.QRect(210, 100, 41, 41))
        self.Btn10Player.setCheckable(True)
        self.Btn10Player.setObjectName(_fromUtf8("Btn10Player"))
        GameSelector.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameSelector)
        QtCore.QObject.connect(self.playtimedial, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(GameSelector)

    def retranslateUi(self, GameSelector):
        GameSelector.setWindowTitle(_translate("GameSelector", "Game Selector", None))
        self.bgcollectionView.setSortingEnabled(True)
        self.dialmaxlabel.setText(_translate("GameSelector", "420", None))
        self.dialminlabel.setText(_translate("GameSelector", "0", None))
        self.bestButton.setText(_translate("GameSelector", "\'Best\'", None))
        self.label.setText(_translate("GameSelector", "Number of\n"
"Players", None))
        self.recommendedButton.setText(_translate("GameSelector", "\'Recommended\'", None))
        self.Btn1Player.setText(_translate("GameSelector", "1", None))
        self.Btn2Player.setText(_translate("GameSelector", "2", None))
        self.Btn3Player.setText(_translate("GameSelector", "3", None))
        self.Btn4Player.setText(_translate("GameSelector", "4", None))
        self.Btn5Player.setText(_translate("GameSelector", "5", None))
        self.Btn6Player.setText(_translate("GameSelector", "6", None))
        self.Btn7Player.setText(_translate("GameSelector", "7", None))
        self.Btn8Player.setText(_translate("GameSelector", "8", None))
        self.Btn9Player.setText(_translate("GameSelector", "9", None))
        self.Btn10Player.setText(_translate("GameSelector", "10", None))

