# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameSelector.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameSelector(object):
    def setupUi(self, GameSelector):
        GameSelector.setObjectName("GameSelector")
        GameSelector.setEnabled(True)
        GameSelector.resize(1819, 992)
        self.centralwidget = QtWidgets.QWidget(GameSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.bgcollectionView = QtWidgets.QTableWidget(self.centralwidget)
        self.bgcollectionView.setGeometry(QtCore.QRect(828, 10, 984, 975))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bgcollectionView.setFont(font)
        self.bgcollectionView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.bgcollectionView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bgcollectionView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bgcollectionView.setAlternatingRowColors(True)
        self.bgcollectionView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bgcollectionView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bgcollectionView.setRowCount(1)
        self.bgcollectionView.setColumnCount(4)
        self.bgcollectionView.setObjectName("bgcollectionView")
        self.bgcollectionView.horizontalHeader().setDefaultSectionSize(50)
        self.bgcollectionView.horizontalHeader().setMinimumSectionSize(1)
        self.bgcollectionView.horizontalHeader().setSortIndicatorShown(True)
        self.bgcollectionView.verticalHeader().setVisible(False)
        self.lcdResults = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdResults.setGeometry(QtCore.QRect(730, 330, 91, 45))
        self.lcdResults.setDigitCount(3)
        self.lcdResults.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdResults.setObjectName("lcdResults")
        self.numPlayerFrame = QtWidgets.QFrame(self.centralwidget)
        self.numPlayerFrame.setGeometry(QtCore.QRect(20, 10, 451, 311))
        self.numPlayerFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.numPlayerFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numPlayerFrame.setObjectName("numPlayerFrame")
        self.bestButton = QtWidgets.QPushButton(self.numPlayerFrame)
        self.bestButton.setEnabled(False)
        self.bestButton.setGeometry(QtCore.QRect(10, 10, 100, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bestButton.setFont(font)
        self.bestButton.setCheckable(True)
        self.bestButton.setObjectName("bestButton")
        self.numplayerLabel = QtWidgets.QLabel(self.numPlayerFrame)
        self.numplayerLabel.setGeometry(QtCore.QRect(119, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.numplayerLabel.setFont(font)
        self.numplayerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numplayerLabel.setObjectName("numplayerLabel")
        self.recommendedButton = QtWidgets.QPushButton(self.numPlayerFrame)
        self.recommendedButton.setEnabled(False)
        self.recommendedButton.setGeometry(QtCore.QRect(249, 10, 191, 75))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.recommendedButton.setFont(font)
        self.recommendedButton.setCheckable(True)
        self.recommendedButton.setObjectName("recommendedButton")
        self.Btn2Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn2Player.setGeometry(QtCore.QRect(10, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn2Player.setFont(font)
        self.Btn2Player.setCheckable(True)
        self.Btn2Player.setObjectName("Btn2Player")
        self.Btn3Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn3Player.setGeometry(QtCore.QRect(120, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn3Player.setFont(font)
        self.Btn3Player.setCheckable(True)
        self.Btn3Player.setObjectName("Btn3Player")
        self.Btn4Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn4Player.setGeometry(QtCore.QRect(230, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn4Player.setFont(font)
        self.Btn4Player.setCheckable(True)
        self.Btn4Player.setObjectName("Btn4Player")
        self.Btn5Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn5Player.setGeometry(QtCore.QRect(340, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn5Player.setFont(font)
        self.Btn5Player.setCheckable(True)
        self.Btn5Player.setObjectName("Btn5Player")
        self.Btn6Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn6Player.setGeometry(QtCore.QRect(10, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn6Player.setFont(font)
        self.Btn6Player.setCheckable(True)
        self.Btn6Player.setObjectName("Btn6Player")
        self.Btn7Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn7Player.setGeometry(QtCore.QRect(120, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn7Player.setFont(font)
        self.Btn7Player.setCheckable(True)
        self.Btn7Player.setObjectName("Btn7Player")
        self.Btn8Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn8Player.setGeometry(QtCore.QRect(230, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn8Player.setFont(font)
        self.Btn8Player.setCheckable(True)
        self.Btn8Player.setObjectName("Btn8Player")
        self.Btn9Player = QtWidgets.QPushButton(self.numPlayerFrame)
        self.Btn9Player.setGeometry(QtCore.QRect(340, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn9Player.setFont(font)
        self.Btn9Player.setCheckable(True)
        self.Btn9Player.setObjectName("Btn9Player")
        self.playTimeFrame = QtWidgets.QFrame(self.centralwidget)
        self.playTimeFrame.setGeometry(QtCore.QRect(480, 10, 341, 311))
        self.playTimeFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.playTimeFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.playTimeFrame.setObjectName("playTimeFrame")
        self.PlayTimeLabel = QtWidgets.QLabel(self.playTimeFrame)
        self.PlayTimeLabel.setGeometry(QtCore.QRect(15, 10, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PlayTimeLabel.setFont(font)
        self.PlayTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PlayTimeLabel.setObjectName("PlayTimeLabel")
        self.Btn30mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn30mins.setGeometry(QtCore.QRect(10, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn30mins.setFont(font)
        self.Btn30mins.setCheckable(True)
        self.Btn30mins.setChecked(False)
        self.Btn30mins.setFlat(False)
        self.Btn30mins.setObjectName("Btn30mins")
        self.Btn60mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn60mins.setGeometry(QtCore.QRect(120, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn60mins.setFont(font)
        self.Btn60mins.setCheckable(True)
        self.Btn60mins.setObjectName("Btn60mins")
        self.Btn90mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn90mins.setGeometry(QtCore.QRect(230, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn90mins.setFont(font)
        self.Btn90mins.setCheckable(True)
        self.Btn90mins.setObjectName("Btn90mins")
        self.Btn120mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn120mins.setGeometry(QtCore.QRect(10, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn120mins.setFont(font)
        self.Btn120mins.setCheckable(True)
        self.Btn120mins.setObjectName("Btn120mins")
        self.Btn150mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn150mins.setGeometry(QtCore.QRect(120, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn150mins.setFont(font)
        self.Btn150mins.setCheckable(True)
        self.Btn150mins.setObjectName("Btn150mins")
        self.Btn180mins = QtWidgets.QPushButton(self.playTimeFrame)
        self.Btn180mins.setGeometry(QtCore.QRect(230, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn180mins.setFont(font)
        self.Btn180mins.setCheckable(True)
        self.Btn180mins.setObjectName("Btn180mins")
        self.tabbedzone = QtWidgets.QTabWidget(self.centralwidget)
        self.tabbedzone.setGeometry(QtCore.QRect(20, 330, 801, 656))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.tabbedzone.setFont(font)
        self.tabbedzone.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabbedzone.setObjectName("tabbedzone")
        self.mechtab = QtWidgets.QWidget()
        self.mechtab.setObjectName("mechtab")
        self.mechaniclist = QtWidgets.QListWidget(self.mechtab)
        self.mechaniclist.setGeometry(QtCore.QRect(-1, -1, 801, 600))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.mechaniclist.setFont(font)
        self.mechaniclist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mechaniclist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mechaniclist.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.mechaniclist.setIconSize(QtCore.QSize(0, 0))
        self.mechaniclist.setObjectName("mechaniclist")
        self.tabbedzone.addTab(self.mechtab, "")
        self.cattab = QtWidgets.QWidget()
        self.cattab.setObjectName("cattab")
        self.categorylist = QtWidgets.QListWidget(self.cattab)
        self.categorylist.setEnabled(True)
        self.categorylist.setGeometry(QtCore.QRect(-1, -1, 801, 600))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.categorylist.setFont(font)
        self.categorylist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.categorylist.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.categorylist.setObjectName("categorylist")
        self.tabbedzone.addTab(self.cattab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.downloadData = QtWidgets.QPushButton(self.tab)
        self.downloadData.setGeometry(QtCore.QRect(10, 10, 150, 100))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.downloadData.setFont(font)
        self.downloadData.setCheckable(False)
        self.downloadData.setChecked(False)
        self.downloadData.setFlat(False)
        self.downloadData.setObjectName("downloadData")
        self.tabbedzone.addTab(self.tab, "")
        self.resetAll = QtWidgets.QPushButton(self.centralwidget)
        self.resetAll.setEnabled(True)
        self.resetAll.setGeometry(QtCore.QRect(561, 326, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resetAll.setFont(font)
        self.resetAll.setObjectName("resetAll")
        self.tabbedzone.raise_()
        self.numPlayerFrame.raise_()
        self.bgcollectionView.raise_()
        self.lcdResults.raise_()
        self.playTimeFrame.raise_()
        self.resetAll.raise_()
        GameSelector.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameSelector)
        self.tabbedzone.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GameSelector)

    def retranslateUi(self, GameSelector):
        _translate = QtCore.QCoreApplication.translate
        GameSelector.setWindowTitle(_translate("GameSelector", "Game Selector"))
        self.bgcollectionView.setSortingEnabled(True)
        self.bestButton.setText(_translate("GameSelector", "Best"))
        self.numplayerLabel.setText(_translate("GameSelector", "<html><head/><body><p>Players</p></body></html>"))
        self.recommendedButton.setText(_translate("GameSelector", "Recommended"))
        self.Btn2Player.setText(_translate("GameSelector", "2"))
        self.Btn3Player.setText(_translate("GameSelector", "3"))
        self.Btn4Player.setText(_translate("GameSelector", "4"))
        self.Btn5Player.setText(_translate("GameSelector", "5"))
        self.Btn6Player.setText(_translate("GameSelector", "6"))
        self.Btn7Player.setText(_translate("GameSelector", "7"))
        self.Btn8Player.setText(_translate("GameSelector", "8"))
        self.Btn9Player.setText(_translate("GameSelector", "9"))
        self.PlayTimeLabel.setText(_translate("GameSelector", "Playing Time"))
        self.Btn30mins.setText(_translate("GameSelector", "0:30"))
        self.Btn60mins.setText(_translate("GameSelector", "1:00"))
        self.Btn90mins.setText(_translate("GameSelector", "1:30"))
        self.Btn120mins.setText(_translate("GameSelector", "2:00"))
        self.Btn150mins.setText(_translate("GameSelector", "2:30"))
        self.Btn180mins.setText(_translate("GameSelector", "3:00"))
        self.tabbedzone.setTabText(self.tabbedzone.indexOf(self.mechtab), _translate("GameSelector", "Mechanism"))
        self.tabbedzone.setTabText(self.tabbedzone.indexOf(self.cattab), _translate("GameSelector", "Theme"))
        self.downloadData.setText(_translate("GameSelector", "Download\n"
"Collection"))
        self.tabbedzone.setTabText(self.tabbedzone.indexOf(self.tab), _translate("GameSelector", "Admin"))
        self.resetAll.setText(_translate("GameSelector", "Reset Filters"))

