# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Dropbox\Coding\GameSelector\GameSelector.ui'
#
# Created: Mon Sep 23 19:30:58 2013
#      by: PyQt5 UI code generator 5.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameSelector(object):
    def setupUi(self, GameSelector):
        GameSelector.setObjectName("GameSelector")
        GameSelector.setEnabled(True)
        GameSelector.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(GameSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.bgcollectionView = QtWidgets.QTableWidget(self.centralwidget)
        self.bgcollectionView.setGeometry(QtCore.QRect(270, 0, 751, 600))
        self.bgcollectionView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bgcollectionView.setAlternatingRowColors(True)
        self.bgcollectionView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bgcollectionView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bgcollectionView.setRowCount(1)
        self.bgcollectionView.setColumnCount(4)
        self.bgcollectionView.setObjectName("bgcollectionView")
        self.bgcollectionView.horizontalHeader().setSortIndicatorShown(False)
        self.bgcollectionView.verticalHeader().setVisible(False)
        self.playtimedial = QtWidgets.QDial(self.centralwidget)
        self.playtimedial.setGeometry(QtCore.QRect(100, 200, 150, 150))
        self.playtimedial.setMaximum(420)
        self.playtimedial.setSingleStep(10)
        self.playtimedial.setPageStep(20)
        self.playtimedial.setNotchesVisible(True)
        self.playtimedial.setObjectName("playtimedial")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 380, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 340, 51, 31))
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.dialmaxlabel = QtWidgets.QLabel(self.centralwidget)
        self.dialmaxlabel.setGeometry(QtCore.QRect(210, 340, 21, 16))
        self.dialmaxlabel.setObjectName("dialmaxlabel")
        self.dialminlabel = QtWidgets.QLabel(self.centralwidget)
        self.dialminlabel.setGeometry(QtCore.QRect(120, 340, 21, 16))
        self.dialminlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dialminlabel.setObjectName("dialminlabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 5, 261, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.bestButton = QtWidgets.QPushButton(self.frame)
        self.bestButton.setEnabled(False)
        self.bestButton.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.bestButton.setCheckable(True)
        self.bestButton.setObjectName("bestButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(75, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.recommendedButton = QtWidgets.QPushButton(self.frame)
        self.recommendedButton.setEnabled(False)
        self.recommendedButton.setGeometry(QtCore.QRect(160, 10, 91, 31))
        self.recommendedButton.setCheckable(True)
        self.recommendedButton.setObjectName("recommendedButton")
        self.Btn1Player = QtWidgets.QPushButton(self.frame)
        self.Btn1Player.setGeometry(QtCore.QRect(10, 50, 41, 41))
        self.Btn1Player.setCheckable(True)
        self.Btn1Player.setChecked(False)
        self.Btn1Player.setFlat(False)
        self.Btn1Player.setObjectName("Btn1Player")
        self.Btn2Player = QtWidgets.QPushButton(self.frame)
        self.Btn2Player.setGeometry(QtCore.QRect(60, 50, 41, 41))
        self.Btn2Player.setCheckable(True)
        self.Btn2Player.setObjectName("Btn2Player")
        self.Btn3Player = QtWidgets.QPushButton(self.frame)
        self.Btn3Player.setGeometry(QtCore.QRect(110, 50, 41, 41))
        self.Btn3Player.setCheckable(True)
        self.Btn3Player.setObjectName("Btn3Player")
        self.Btn4Player = QtWidgets.QPushButton(self.frame)
        self.Btn4Player.setGeometry(QtCore.QRect(160, 50, 41, 41))
        self.Btn4Player.setCheckable(True)
        self.Btn4Player.setObjectName("Btn4Player")
        self.Btn5Player = QtWidgets.QPushButton(self.frame)
        self.Btn5Player.setGeometry(QtCore.QRect(210, 50, 41, 41))
        self.Btn5Player.setCheckable(True)
        self.Btn5Player.setObjectName("Btn5Player")
        self.Btn6Player = QtWidgets.QPushButton(self.frame)
        self.Btn6Player.setGeometry(QtCore.QRect(10, 100, 41, 41))
        self.Btn6Player.setCheckable(True)
        self.Btn6Player.setObjectName("Btn6Player")
        self.Btn7Player = QtWidgets.QPushButton(self.frame)
        self.Btn7Player.setGeometry(QtCore.QRect(60, 100, 41, 41))
        self.Btn7Player.setCheckable(True)
        self.Btn7Player.setObjectName("Btn7Player")
        self.Btn8Player = QtWidgets.QPushButton(self.frame)
        self.Btn8Player.setGeometry(QtCore.QRect(110, 100, 41, 41))
        self.Btn8Player.setCheckable(True)
        self.Btn8Player.setObjectName("Btn8Player")
        self.Btn9Player = QtWidgets.QPushButton(self.frame)
        self.Btn9Player.setGeometry(QtCore.QRect(160, 100, 41, 41))
        self.Btn9Player.setCheckable(True)
        self.Btn9Player.setObjectName("Btn9Player")
        self.Btn10Player = QtWidgets.QPushButton(self.frame)
        self.Btn10Player.setGeometry(QtCore.QRect(210, 100, 41, 41))
        self.Btn10Player.setCheckable(True)
        self.Btn10Player.setObjectName("Btn10Player")
        GameSelector.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameSelector)
        self.playtimedial.valueChanged['int'].connect(self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(GameSelector)

    def retranslateUi(self, GameSelector):
        _translate = QtCore.QCoreApplication.translate
        GameSelector.setWindowTitle(_translate("GameSelector", "Game Selector"))
        self.bgcollectionView.setSortingEnabled(True)
        self.dialmaxlabel.setText(_translate("GameSelector", "420"))
        self.dialminlabel.setText(_translate("GameSelector", "0"))
        self.bestButton.setText(_translate("GameSelector", "\'Best\'"))
        self.label.setText(_translate("GameSelector", "Number of\n"
"Players"))
        self.recommendedButton.setText(_translate("GameSelector", "\'Recommended\'"))
        self.Btn1Player.setText(_translate("GameSelector", "1"))
        self.Btn2Player.setText(_translate("GameSelector", "2"))
        self.Btn3Player.setText(_translate("GameSelector", "3"))
        self.Btn4Player.setText(_translate("GameSelector", "4"))
        self.Btn5Player.setText(_translate("GameSelector", "5"))
        self.Btn6Player.setText(_translate("GameSelector", "6"))
        self.Btn7Player.setText(_translate("GameSelector", "7"))
        self.Btn8Player.setText(_translate("GameSelector", "8"))
        self.Btn9Player.setText(_translate("GameSelector", "9"))
        self.Btn10Player.setText(_translate("GameSelector", "10"))

